LLM_MODEL = 'microsoft/Phi-3-mini-4k-instruct'
EMBEDDING_MODEL = 'sentence-transformers/all-mpnet-base-v2'
RETRIEVE = 'retrieve_documents'
GRADE_DOCUMENTS = 'grade_documents'
WEB_SEARCH = 'websearch'
GENERATE = 'generate'
